import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GalleryHorizontal, Home, User } from "lucide-react";
import { FloatingNav } from "@/components/ui/floating-nabar";
import { cn } from "@/lib/utils";
import Footer from "@/components/ui/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 const navItems = [
    {
      name: "Accueil",
      link: "#home",
      icon: <Home className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
    {
      name: "A Propos",
      link: "#about",
      icon: <User className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
    {
      name: "Projets",
      link: "#project",
      icon: <GalleryHorizontal className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
  
    {
      name: "Contact",
      link: "#contact",
      icon: <GalleryHorizontal className="h-4 w-4 text-neutral-500 dark:text-white" />,
    },
  
  ]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={cn(
          " bg-background font-sans antialiased",
         
        )}
      >
        <FloatingNav navItems={navItems} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
